main:
  - identifier: home
    name: Kunst
    url: /kunst/
    weight: 2
  - identifier: portfolio
    name: Portfolio
    url: /#project-portfolio
    weight: 3
  - identifier: contact
    name: Kontakt
    url: /#contact
    weight: 4
