main:
  - identifier: home
    name: Home
    pageRef: /
    weight: 1
  - identifier: art
    name: Arte
    pageRef: /kunst
    weight: 2
  - identifier: cases
    name: Casi
    pageRef: /cases
    weight: 3
  - identifier: contact
    name: Contatto
    pageRef: /contact
    weight: 5
