main:
  - identifier: home
    name: 首页
    pageRef: /
    weight: 1
  - identifier: art
    name: 艺术
    pageRef: /kunst
    weight: 2
  - identifier: cases
    name: 案例
    pageRef: /cases
    weight: 3
  - identifier: biennale
    name: 双年展
    url: /biennalevenetie2026/
    weight: 4
  - identifier: contact
    name: 联系方式
    pageRef: /contact
    weight: 5
