main:
  - identifier: home
    name: 首页
    url: /
    weight: 1
  - identifier: art
    name: 艺术
    url: /艺术/
    weight: 2
  - identifier: portfolio
    name: 项目组合
    url: /#project-portfolio
    weight: 3
  - identifier: contact
    name: 联系方式
    url: /#contact
    weight: 4
