main:
  - identifier: home
    name: Home
    pageRef: /
    weight: 1
  - identifier: cases
    name: Fallstudien
    pageRef: /cases
    weight: 2
  - identifier: kunst
    name: Kunst
    pageRef: /kunst
    weight: 3
  - identifier: contact
    name: Kontakt
    pageRef: /contact
    weight: 5
