main:
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: kunst
    name: Kunst
    url: /kunst/
    weight: 2
  - identifier: contact
    name: Contact
    url: /#contact
    weight: 3
