main:
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: art
    name: Arte
    url: /arte/
    weight: 2
  - identifier: contact
    name: Contatto
    url: /#contact
    weight: 3
