main:
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: art
    name: Art
    url: /art/
    weight: 2
  - identifier: contact
    name: Contact
    url: /#contact
    weight: 3
