baseURL: "https://marcovanthiel.nl/"
languageCode: "nl"
title: "Marco van Thiel"
theme: "marcotheme"
# Multilingual settings
defaultContentLanguage: "nl"
defaultContentLanguageInSubdir: false
languages:
  nl:
    languageName: "Nederlands"
    weight: 1
    contentDir: "content/nl"
    title: "Marco van Thiel - Interim manager, CIO, Programmamanager en Projectmanager"
    params:
      description: "Marco van Thiel - Interim manager, CIO, Programmamanager en Projectmanager"
  en:
    languageName: "English"
    weight: 2
    contentDir: "content/en"
    title: "Marco van Thiel - Interim manager, CIO, Program manager and Project manager"
    params:
      description: "Marco van Thiel - Interim manager, CIO, Program manager and Project manager"
  de:
    languageName: "Deutsch"
    weight: 3
    contentDir: "content/de"
    title: "Marco van Thiel - Interimsmanager, CIO, Programmmanager und Projektmanager"
    params:
      description: "Marco van Thiel - Interimsmanager, CIO, Programmmanager und Projektmanager"
  it:
    languageName: "Italiano"
    weight: 4
    contentDir: "content/it"
    title: "Marco van Thiel - Manager ad interim, CIO, Program manager e Project manager"
    params:
      description: "Marco van Thiel - Manager ad interim, CIO, Program manager e Project manager"
  cn:
    languageName: "中文"
    weight: 5
    contentDir: "content/cn"
    title: "Marco van Thiel - 临时经理, CIO, 项目经理"
    params:
      description: "Marco van Thiel - 临时经理, CIO, 项目经理"
# Site parameters
params:
  author: "Marco van Thiel"
  description: "Marco van Thiel - Interim manager, CIO, Programmamanager en Projectmanager"
  mainSections: ["posts"]
  contact:
    email: "marco@marcovanthiel.nl"
    phone: "+31 (0)6 54 211 659"
    linkedin: "https://www.linkedin.com/in/marcovanthiel/"
    address: "Nijmegen, Nederland"
  
# Menu configuration will be added later
